# THIS FILE INCLUDES ALL PRE-DEFINED PARAMETERS FOR 
# THE PROCESS OF R2D2 SOUND GENERATION

SAMPLE_RATE = 16000
AMPLITUDE_SCALE = 0.5
DEF_CUTOFF_FREQUENCY = 4000
AVG_LENGTH = 30  #average length of each r2d2 audio

NUM_AUDIOS = 300 # number of audios to generate
